[package]
name = "sqs_extended_client_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.2"
aws-sdk-s3 = "1.98.0"
aws-sdk-sqs = "1.76.0"
tokio = { version = "1.46.1", features = ["full"] }

[dev-dependencies]
mockall = "0.13.1"
