name: Lint (Clippy)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install clippy
        run: rustup component add clippy

      - name: Run rust-clippy
        run:
          cargo clippy
          --release
          --all-features
          --all-targets
          -- -D warnings
